modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "shadowconfig"
version = "${version}"
displayName = "Shadow Config"
authors = "ShadowKing21"
description = '''
Extensible configuration library for mods, designed to simplify config management with many functions and multiple file extensions
'''
logoFile = "assets/shadowconfig/icon.png"

[[dependencies.shadowconfig]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shadowconfig]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shadowconfig]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
